require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'FACEIT' do
  # React Native pods
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'

 pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
  #   workaround to build app locally on xcode14 to avoid this error: https://github.com/CocoaPods/CocoaPods/issues/11402
#     installer.pods_project.targets.each do |target|
#            if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
#              target.build_configurations.each do |config|
#                  config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#              end
#            end
#          end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
